[[permission]]
identifier = "allow-connection-commands"
description = "Allows JDBC connection management through jdbc-agent."
commands.allow = [
  "connection_connect",
  "connection_disconnect",
  "connection_test",
  "connection_metadata",
  "connection_prefetch_catalog",
  "connection_find_objects_by_name",
  "connection_columns",
  "connection_arguments",
  "connection_package_members",
  "connection_primary_keys",
  "connection_ddl",
  "connection_compile",
  "connection_commit",
  "connection_rollback",
  "connection_indexes",
  "connection_table_comment",
  "connection_references",
  "connection_foreign_keys",
  "connection_constraints",
  "connection_triggers",
  "connection_dependencies",
  "connection_dependents",
  "connection_set_catalog",
  "connection_set_schema",
]
