/** Standard AWS public-partition regions, for the SSM tunnel Region field's suggestion list.
 *  A plain text input backs this (not a rigid <select>) — AWS adds new regions over time and
 *  users should never be blocked from typing one this list doesn't have yet. */
export const AWS_REGIONS: string[] = [
  "us-east-1",
  "us-east-2",
  "us-west-1",
  "us-west-2",
  "af-south-1",
  "ap-east-1",
  "ap-south-1",
  "ap-south-2",
  "ap-northeast-1",
  "ap-northeast-2",
  "ap-northeast-3",
  "ap-southeast-1",
  "ap-southeast-2",
  "ap-southeast-3",
  "ap-southeast-4",
  "ca-central-1",
  "ca-west-1",
  "eu-central-1",
  "eu-central-2",
  "eu-west-1",
  "eu-west-2",
  "eu-west-3",
  "eu-north-1",
  "eu-south-1",
  "eu-south-2",
  "me-south-1",
  "me-central-1",
  "sa-east-1",
  "il-central-1",
];
